// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("CRMSvcUtilExtensions")]
[assembly: AssemblyDescriptionAttribute("A library with extensions to CRMSvcUtil")]
[assembly: AssemblyProductAttribute("CRMSvcUtilExtensions")]
[assembly: GuidAttribute("76e6ae49-230a-472b-a132-e8ad2f821e64")]
[assembly: AssemblyVersionAttribute("2.0.0")]
[assembly: AssemblyFileVersionAttribute("2.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "CRMSvcUtilExtensions";
        internal const System.String AssemblyDescription = "A library with extensions to CRMSvcUtil";
        internal const System.String AssemblyProduct = "CRMSvcUtilExtensions";
        internal const System.String Guid = "76e6ae49-230a-472b-a132-e8ad2f821e64";
        internal const System.String AssemblyVersion = "2.0.0";
        internal const System.String AssemblyFileVersion = "2.0.0";
    }
}
